#!/bin/bash
clear
if ! [ -x "$(command -v wget)" ]; then
  echo "* curl is required in order for this script to work."
  echo "* install using apt (Debian and derivatives) or yum/dnf (CentOS)"
  exit 1
fi
echo "_______________________________________________"
echo ""
echo "MC Server Installer Script | Made by WavaAdrian"
echo ""
echo "_______________________________________________"
sleep 4
sudo apt update
sudo apt install openjdk-17-jdk -y
echo "_______________________________________________"
echo ""
echo "Installed OpenJDK17"
echo ""
echo "_______________________________________________"
sleep 3
sudo apt install screen -y
echo "_______________________________________________"
echo ""
echo "Installed Screen"
echo ""
echo "_______________________________________________"
sleep 3
mkdir minecraft
echo "_______________________________________________"
echo ""
echo "Created A Folder Called minecraft"
echo ""
echo "_______________________________________________"
sleep 3
cd minecraft
sudo apt install wget
sudo wget https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar
echo "_______________________________________________"
echo ""
echo "Done Installing Minecraft Server Jar file."
echo ""
echo "_______________________________________________"
sleep 3
sudo wget https://bigheartedgiantnumericalanalysis.adrianleanderle.repl.co/start.sh
echo "_______________________________________________"
echo ""
echo "Done Installing Start Script."
echo ""
echo "_______________________________________________"
sleep 2
echo "Now Follow My Youtube Video How to do it: [Soon] | Or Follow the steps after you have run the script on github."
exit
